Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ""
    aws.secret_access_key = ""
    aws.keypair_name = ""
    aws.security_groups = ""
    aws.ami = ""
    aws.iam_instance_profile_arn = ""
    aws.instance_type = "t2.medium"
    aws.subnet_id = ""
    aws.ssh_host_attribute = "private_ip_address"
    aws.private_ip_address = ""
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = ""
    aws.user_data = File.read("./userData/")
    aws.tags = {
    'Name' => 'Cron',
    'Admin' => 'Adam Arredondo',
    'Purpose' => 'Business critical cron jobs',
    'Version' => ''
    }
  end
end
