Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ""
    aws.secret_access_key = ""
    aws.keypair_name = ""
    aws.security_groups = ""
    aws.ami = ""
    aws.instance_type = "t2.small"
    aws.subnet_id = ""
    associate_public_ip = "true"
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = ""
    aws.tags = {
    'Name' => 'Logstash',
    'Admin' => '',
    'Purpose' => ''
    }
  end
end
